### ISSUE TITLE
Custom settings ignored

### ISSUE THREAD

**Issue by Huntingtor** [Prosk8er/Snowstorm-Lights#18]
My phpBB version: 3.3.10 - newly installed test board, no other extensions, prosilver template. Server: managed hosting with PHP 8.1.24 and Apache.

Whatever I configure in snowstorm.js, _all_ custom settings are ignored.
I cleared forum cache and browser cache - no effect. Tested under Windows 10 Pro with Chrome and Firefox. What I'm missing?

**Comment by Prosk8er** [comment]
That's because it doesn't use that file it uses [this one](https://github.com/Prosk8er/Snowstorm-Lights/blob/master/styles/all/template/snowstorm/snowstorm-min.js) by default
to use the one your editing change this https://github.com/Prosk8er/Snowstorm-Lights/blob/ec04fc248ea58fb69b94ace461193cd989578e57/styles/all/template/event/overall_header_stylesheets_after.html#L12C12-L12C12

**Comment by Huntingtor** [comment]
Thank you for your quick response. Unfortunately, including snowstorm.js stops the snowfall entirely.

The firefox extension _JavaScript Errors Notifier_ shows this error:
`ReferenceError: f is not defined /phpbb/ext/prosk8er/snowstormlights/styles/all/template/snowstorm/snowstorm.js?assets_version=640:29`

**Comment by Prosk8er** [comment]
check any changes you did to that file cause its working for me

**Comment by Huntingtor** [comment]
Indeed, I messed up something in the config section. Now it works flawlessly. Sorry for the false alarm. Issue solved.
Have a nice day and happy holidays.

**Comment by Prosk8er** [comment]
ok glad you got it working happy holidays
